### PR TITLE
Add 2 PRs 

### PR DESCRIPTION
**Pull request by gadmm**
Hello, I would like to benchmark these two OCaml PRs please.

I have also added some fixes to the Makefile to run it locally.

### CODE REVIEW

**Comment by shakthimaan** [comment]
LGTM!

**Comment by gadmm** [comment]
Thanks.

I think the archive format I have submitted (`refs/pull`) will not be handled by the script function below:

https://github.com/ocaml-bench/sandmark/blob/c6b4d24b8c09b5af4ba1877743da79f149d3d5d0/run_all_custom.sh#L37-L40

It looks like it is not going to work. If so, the simplest might be to adapt the lines above to also work with `refs/pull`.

**Comment by gadmm** [comment]
(I could also change for a `refs/heads` URL, but `refs/pull` is very convenient!)

**Comment by gadmm** [comment]
The benchmarks run correctly, but it does not detect the commit hash properly, leading to not storing which commit hash has been tested in a particular run. This makes it impossible to know what exactly has been benchmarked if we don't keep track separately.

**Pull request merged**
